version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      production-dependencies:
        dependency-type: "production"
      typescript-eslint:
        patterns:
          - "typescript"
          - "typescript-eslint"
          - "@typescript-eslint/*"
          - "eslint"
          - "eslint-*"
      jest:
        patterns:
          - "jest"
          - "@types/jest"
          - "ts-jest"
      semantic-release:
        patterns:
          - "semantic-release"
          - "@semantic-release/*"
          - "commitizen"
          - "@commitlint/*"
      type-definitions:
        patterns:
          - "@types/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      github-actions:
        patterns:
          - "*"
