import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import spellcheck from 'eslint-plugin-spellcheck';

export default tseslint.config(
  {
    ignores: ['dist/**', 'node_modules/**'],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['src/**/*.ts'],
    plugins: {
      spellcheck,
    },
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: {
        ecmaVersion: 2018,
        sourceType: 'module',
      },
    },
    rules: {
      'quotes': ['warn', 'single'],
      'indent': ['warn', 2, { 'SwitchCase': 1 }],
      'semi': ['off'],
      'spellcheck/spell-checker': [
        'warn',
        {
          'strings': false,
          'skipWords': [
            'accessors',
            'activityType',
            'axios',
            'blwrpm',
            'bryant',
            'cdata',
            'cfgdead',
            'cfgem',
            'cfgfan',
            'cfghumid',
            'cfguv',
            'cfgvent',
            'clsp',
            'cmode',
            'coolingKwh',
            'ctype',
            'damperposition',
            'dataservice',
            'dayId',
            'deadband',
            'Dehum',
            'dehumidification',
            'eHeatKwh',
            'eheat',
            'emailVerified',
            'energyConfig',
            'energyPeriodType',
            'energyPeriods',
            'etag',
            'Fanv',
            'fanGasKwh',
            'fanKwh',
            'fangas',
            'fanonly',
            'featureset',
            'filterinterval',
            'filtertype',
            'filtrlvl',
            'fueltype',
            'gasKwh',
            'gasunit',
            'graphql',
            'hPHeatKwh',
            'heatsource',
            'holdActivity',
            'Homebridge',
            'hpheat',
            'hspf',
            'htsp',
            'humidifier',
            'humidityAway',
            'humidityHome',
            'humidityVacation',
            'humlvl',
            'identityId',
            'idu',
            'idusource',
            'idutype',
            'indoorModel',
            'indoorSerial',
            'infinityEnergy',
            'infinitySystems',
            'iot',
            'isDisconnected',
            'Kwh',
            'localTime',
            'localTimeOffset',
            'locationId',
            'loopPumpKwh',
            'looppump',
            'memoization',
            'mutex',
            'nonces',
            'oat',
            'occ',
            'occEnabled',
            'Okta',
            'odu',
            'odutype',
            'opstat',
            'otmr',
            'outdoorModel',
            'outdoorSerial',
            'rclg',
            'rclgovercool',
            'reheat',
            'reheatKwh',
            'rh',
            'rhtg',
            'Retryable',
            'seer',
            'setpoint',
            'setpoints',
            'sig',
            'statpress',
            'svalue',
            'thingName',
            'timestamps',
            'oauth',
            'unregister',
            'userName',
            'utcTime',
            'uvlvl',
            'vacat',
            'vacatrunning',
            'vacend',
            'vacfan',
            'vacmaxt',
            'vacmint',
            'vacstart',
            'vent',
            'ventclg',
            'venthtg',
            'ventlvl',
            'ventspdclg',
            'ventspdhtg',
            'wc',
            'wcTime',
            'xml',
            'xml2js',
            'zoneId',
            'zoneconditioning',
          ],
        },
      ],
      'comma-dangle': ['warn', 'always-multiline'],
      'dot-notation': 'off',
      'eqeqeq': 'warn',
      'curly': ['warn', 'all'],
      'brace-style': ['warn'],
      'prefer-arrow-callback': ['warn'],
      'max-len': ['warn', 140],
      'no-console': ['warn'],
      'comma-spacing': ['error'],
      'no-multi-spaces': ['warn', { 'ignoreEOLComments': true }],
      'no-trailing-spaces': ['warn'],
      'lines-between-class-members': ['warn', 'always', { 'exceptAfterSingleLine': true }],
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/explicit-module-boundary-types': 'off',
    },
  },
);
