name: Release

on:
  push:
    branches:
      - master
      - beta

jobs:
  build:
    uses: ./.github/workflows/build.yml
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
    needs: [build]
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
